apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: testprojectkube
  template:
    metadata:
      labels:
        app: testprojectkube
    spec:
      containers:
      - name: my-container
        image: lucasbogaard/test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: testprojectkube
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: testprojectkube